package locker.event;

public enum UIEvent {
    SOURCE_FILE_SELECTED,
    DESTINATION_FILE_SELECTED,
    OPERATION_MODE_SELECTED,
    SAVE_PREFERENCE,
    LOAD_PREFERENCE,
    LOAD_PREFERENCE_ERROR,
    START
}
