package locker.event;

public enum UIEvent {
    SOURCE_FILE_SELECTED,
    DESTINATION_FILE_SELECTED,
    OPERATION_MODE_SELECTED,
    SAVE_PREFERENCE,
    LOAD_PREFERENCE,
    REMOVE_PREFERENCE,
    IMPORT_PREFERENCES,
    EXPORT_PREFERENCES,
    START
}
